name: Build Workflow

on:
  push:
    paths-ignore:
      - '.vscode'
      - 'README.md'
      - 'TODO.md'
  pull_request:
    paths-ignore:
      - '.vscode'
      - 'README.md'
      - 'TODO.md'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container: haxe:latest
    name: "Build with Haxe"
    outputs:
      commit_tag: ${{ steps.build.outputs.commit_tag }}
      commit_message: ${{ steps.build.outputs.commit_message }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Cache haxelib
        uses: actions/cache@v2
        with:
          path: /haxelib
          key: haxelib-cache

      - name: Cache Export
        uses: actions/cache@v2
        with:
          path: {{ github.workspace }}/Export
          key: export-cache

      - name: Install library
        run: |
          apt-get update
          apt-get install build-essential -y
          haxe --version
          haxelib setup /haxelib
          haxelib install openfl --always --quiet
          haxelib install lime --always --quiet
          haxelib git starling https://github.com/openfl/starling.git --always --quiet
          echo "y" | haxelib --always --quiet run openfl setup

      - name: Build
        run: |
          haxelib run openfl build html5
          haxelib run openfl build linux
          haxelib run openfl build windows

      - name: "Upload artefact"
        uses: actions/upload-artifact@v2
        with:
          name: "html5"
          path: Export/html5/bin

      - name: "Upload artefact"
        uses: actions/upload-artifact@v2
        with:
          name: "linux"
          path: Export/linux/bin

      - name: "Upload artefact"
        uses: actions/upload-artifact@v2
        with:
          name: "window"
          path: Export/window/bin