name: Build Workflow

on:
  push:
    paths-ignore:
      - '.vscode'
      - 'README.md'
      - 'TODO.md'
  pull_request:
    paths-ignore:
      - '.vscode'
      - 'README.md'
      - 'TODO.md'
  release:
    types: [created]

env:
  HAXE_VERSION: 4.1.4

jobs:
  install-library:
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Cache haxelib
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/haxelib
          key: haxelib-cache

      - name: Install library
        run: |
          haxe --version
          haxelib setup "$GITHUB_WORKSPACE"/haxelib
          haxelib install openfl --always --quiet
          haxelib install lime --always --quiet
          haxelib git starling https://github.com/openfl/starling.git --always --quiet
          echo "y" | haxelib --always --quiet run openfl setup

  build-html5:
    needs: install-library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Cache haxelib
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/haxelib
          key: haxelib-cache

      - name: "Compile"
        run: |
          haxelib setup "$GITHUB_WORKSPACE"/haxelib
          haxelib run openfl build html5

      - name: "Upload artefact"
        uses: actions/upload-artifact@v2
        with:
          name: "html5"
          path: Export/html5/bin

  build-linux:
    needs: install-library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Cache haxelib
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/haxelib
          key: haxelib-cache

      # - name: "Install build tools"
      #   run: |
      #     apt-get update
      #     apt-get install build-essential -y

      - name: "Compile"
        run: |
          haxelib setup "$GITHUB_WORKSPACE"/haxelib
          haxelib run openfl build linux -64

      - name: "Upload artefact"
        uses: actions/upload-artifact@v2
        with:
          name: "linux_x64"
          path: Export/linux/bin

  build-linux32:
    needs: install-library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Cache haxelib
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/haxelib
          key: haxelib-cache

      - name: "Install multilib"
        run: |
          apt-get update
          apt-get install g++-multilib -y

      - name: "Compile"
        run: |
          haxelib setup "$GITHUB_WORKSPACE"/haxelib
          haxelib run openfl build linux -32

      - name: "Upload artefact"
        uses: actions/upload-artifact@v2
        with:
          name: "linux_x86"
          path: Export/linux/bin
  
  build-windows:
    needs: install-library
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Cache haxelib
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/haxelib
          key: haxelib-cache

      - name: "Compile"
        run: |
          haxelib setup %GITHUB_WORKSPACE%/haxelib
          haxelib run openfl build windows -64

      - name: "Upload artefact"
        uses: actions/upload-artifact@v2
        with:
          name: "windows_x64"
          path: Export/windows/bin
  
  build-windows32:
    needs: install-library
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ env.HAXE_VERSION }}

      - name: Cache haxelib
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/haxelib
          key: haxelib-cache

      - name: "Compile"
        run: |
          haxelib setup %GITHUB_WORKSPACE%/haxelib
          haxelib run openfl build windows -32

      - name: "Upload artefact"
        uses: actions/upload-artifact@v2
        with:
          name: "windows_x86"
          path: Export/windows/bin

