name: Build Workflow

on:
  push:
    paths-ignore:
      - '.vscode'
      - 'README.md'
      - 'TODO.md'
  pull_request:
    paths-ignore:
      - '.vscode'
      - 'README.md'
      - 'TODO.md'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.4

      - run: haxe -version
      - run: haxelib install openfl --always --quiet
      - run: haxelib install lime --always --quiet
      - run: haxelib git starling https://github.com/openfl/starling.git --always --quiet
      - run: echo "y" | haxelib run openfl setup

      - name: "Compile"
        run: haxelib run openfl build html5

      - name: "Upload artefact"
        uses: actions/upload-artifact@v2
        with:
          name: "html5"
          path: Export/html5/bin

  # install-library:
  #   runs-on: ubuntu-latest
  #   container: haxe:latest
    
  #   steps:
  #     - name: "Checkout"
  #       uses: actions/checkout@v2

  #     - name: Cache haxelib
  #       uses: actions/cache@v2
  #       with:
  #         path: /haxelib
  #         key: haxelib-cache

  #     - name: Install library
  #       run: |
  #         haxe --version
  #         haxelib setup /haxelib
  #         haxelib install openfl --always --quiet
  #         haxelib install lime --always --quiet
  #         haxelib git starling https://github.com/openfl/starling.git --always --quiet
  #         echo "y" | haxelib --always --quiet run openfl setup

  # build-html5:
  #   needs: install-library
  #   runs-on: ubuntu-latest
  #   container: haxe:latest
    
  #   steps:
  #     - name: "Checkout"
  #       uses: actions/checkout@v2

  #     - name: Cache haxelib
  #       uses: actions/cache@v2
  #       with:
  #         path: /haxelib
  #         key: haxelib-cache

  #     - name: Cache build file
  #       uses: actions/cache@v2
  #       with:
  #         path: Export/html5
  #         key: html5-cache

  #     - name: "Build"
  #       run: |
  #         haxelib setup /haxelib
  #         haxelib run openfl build html5

  #     - name: "Upload artefact"
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: "html5"
  #         path: Export/html5/bin