name: Build html5

on:
  push:
    paths-ignore:
      - '.vscode'
      - 'README.md'
      - 'TODO.md'
  pull_request:
    paths-ignore:
      - '.vscode'
      - 'README.md'
      - 'TODO.md'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    container: haxe:latest
    name: "Build with Haxe"
    outputs:
      commit_tag: ${{ steps.build.outputs.commit_tag }}
      commit_message: ${{ steps.build.outputs.commit_message }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Install library
        run: |
          haxe --version
          haxelib setup /haxelib
          haxelib install openfl --always
          haxelib install lime --always
          haxelib git starling https://github.com/openfl/starling.git --always
          echo "y" | haxelib run openfl setup

      - name: Build
        run: openfl build html5